/// Flutter icons Customicon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Customicon
///      fonts:
///       - asset: fonts/Customicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Customicon {
  Customicon._();

  static const _kFontFam = 'Customicon';
  static const String? _kFontPkg = null;

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
